services:
  whisper-rocm:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: whisper-api:rocm-5.7
    container_name: whisper-api
    restart: unless-stopped

    environment:
      HOST: ${HOST}
      PORT: ${PORT}

    ports:
      - "${PORT}:${PORT}"

    # To allow Docker access to the AMD GPU
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
    shm_size: 8G

    volumes:
      - ./outputs:outputs/
      - ./whisper-model:whisper-model/
      - ./uploads:uploads/

    env_file:
      - .env

    command: ["python", "api.py"]