#################################################
#### SETUP ROCM-5.7 and CLBlas and rocBLAS  #####
#################################################
FROM rocm/dev-ubuntu-22.04:5.7 AS rocm

# Login as root user.    
USER root

# Install dependencies and rocm-5.7
RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \ 
    sudo wget git cmake rocsparse-dev hipsparse-dev rocthrust-dev rocblas-dev hipblas-dev make build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY sudo-nopasswd /etc/sudoers.d/sudo-nopasswd
RUN useradd --create-home -G sudo,video --shell /bin/bash rocm-user
USER rocm-user
WORKDIR /home/rocm-user
ENV PATH "${PATH}:/opt/rocm/bin"

##################################
######### SETUP CLBLAST  #########
##################################
FROM rocm AS rocm-clblas

# Login as root user.    
USER root

# Set env for building and installing clblas
ENV HSA_OVERRIDE_GFX_VERSION=10.3.0
RUN git clone https://github.com/CNugteren/CLBlast.git && \
  cd CLBlast && \
  mkdir build && \
  cd build && \
  cmake .. && \
  make && \
  make install

#######################################
########## INSTALL CLBLAST  ###########
####################################### 
FROM rocm-clblas AS clblas-installer

ENV ROCM_PATH=/opt/rocm
ENV CLBlast_DIR=/usr/lib/cmake/CLBlast
USER rocm-user

RUN sudo apt-get update && sudo apt-get upgrade -y \
    && sudo apt-get install -y git \ 
    gcc \
    build-essential \
    python3 python3-pip \
    ocl-icd-opencl-dev opencl-headers clinfo \
    libclblast-dev libopenblas-dev libaio-dev \
    && mkdir -p /etc/OpenCL/vendors && echo "libamdrocopencl.so" | sudo tee /etc/OpenCL/vendors/amd.icd \
    && sudo ln -s /usr/bin/python3 /usr/bin/python


#######################################
########### SETUP WHISPER  ############
####################################### 
FROM clblas-installer AS whisper-base

# Install specific packages using pip
RUN apt-get update -y \
    && apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    sudo ffmpeg nano wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# # Login as rocm-user.    
USER rocm-user
ENV PATH="/home/rocm-user/.local/bin:${PATH}"

# Install specific packages using pip
COPY . .
RUN pip install datasets ipywidgets transformers numba openai-whisper -q
RUN pip install -U pip
RUN pip install gradio

# Install dependencies and rocm-5.7
# RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.7
RUN pip install torch torchaudio --index-url https://download.pytorch.org/whl/rocm5.7
RUN pip install --no-cache-dir --no-deps -r requirements.txt

# Download test file:
RUN wget https://www2.cs.uic.edu/~i101/SoundFiles/preamble.wav

# Startup script
# ENV HOST 0.0.0.0
ENV GRADIO_SERVER_NAME="0.0.0.0"
EXPOSE 7860
CMD ["python", "app.py"]